name: Continuous Deployment

on:
    push:
        branches:
            - 'main'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref_name }}
    cancel-in-progress: true
    
jobs:

    publish:
        uses: srinivas-kujala/.github/workflows/publish-sdk.yml@main
        with:
          branch-name: ${{ github.ref_name }}
          project-path: ${{ vars.PROJECT_PATH }}
        secrets:
          jfrog-password: ${{ secrets.JFROG_PASSWORD }}
          jfrog-access-token: ${{ secrets.JFROG_TOKEN }}